
import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import { SessionProvider } from 'next-auth/react'
import CreateModal from '@/components/modals/CreateModal'
import EditModal from '@/components/modals/EditModal'
import { CreateProvider } from '@/providers/create-provider'
import { EditProvider } from '@/providers/edit-provider'
import TosatProvider from '@/providers/toast-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Promptopia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Provider >
        <div className='main'>
        <div className='gradient'/>
        </div>
        <main className= 'relative z-10 flex justify-center items-center flex-col max-w-7xl mx-auto sm:px-16 px-6'>
  
      
        <Navbar/>
        <CreateProvider/>
       <TosatProvider/>
        {children}
        </main>
        </Provider>
        </body>
    </html>
  )
}
